---
- name: Respond to Gitea events
  hosts: all
  sources:
    - name: range
      ansible.eda.range:
        limit: 5
  
  rules:

    - name: debug with var
      condition: event.i >= 3
      action:
         debug:
           var: event.i
